# examples/chaperone_demo.py
from pydantic import BaseModel, Field
from operon.organelles.chaperone import Chaperone

# --- 1. DEFINE THE TARGET STRUCTURE (The "DNA" Blueprint) ---
class SQLQuery(BaseModel):
    """The required shape of the output protein."""
    query_type: str = Field(..., pattern="^(SELECT|INSERT|UPDATE)$")
    table_name: str
    parameters: dict
    estimated_cost: int

# Initialize the organelle
chap = Chaperone()

print("--- TEST 1: SUCCESSFUL FOLDING ---")
# A perfect raw string generated by an LLM
good_peptide = """
{
    "query_type": "SELECT",
    "table_name": "users",
    "parameters": {"region": "us-east"},
    "estimated_cost": 10
}
"""
protein_ok = chap.fold(good_peptide, SQLQuery)

if protein_ok.valid:
    # We can now safely access dotted attributes. The IDE knows it's an SQLQuery object.
    print(f"Result: Accessing table '{protein_ok.structure.table_name}'")


print("\n--- TEST 2: MISFOLD (Schema Violation) ---")
# The LLM hallucinated an invalid query_type and forgot the cost
bad_peptide = """
{
    "query_type": "DELETE", 
    "table_name": "users",
    "parameters": {"id": 123}
}
"""
protein_bad = chap.fold(bad_peptide, SQLQuery)

if not protein_bad.valid:
    # This error trace is usually fed back to the LLM in the next prompt
    # to induce a "Refolding" attempt.
    print("Misfold Trace for LLM feedback:")
    print(protein_bad.error_trace)

print("\n--- TEST 3: CRITICAL MISFOLD (Invalid JSON) ---")
# The LLM just outputted raw text
ugly_peptide = "Here is the query you asked for: SELECT * FROM users"
protein_ugly = chap.fold(ugly_peptide, SQLQuery)
print(protein_ugly.error_trace)
